version: '3'

volumes:
  postgres_data:

# container services
services:
  db:
    # ref: https://hub.docker.com/_/postgres
    image: postgres
    restart: always
    # ports:
    #   - "15432:5432"
    expose:
      - 5432
    env_file:
      - ./.env
    # environment:
      # - POSTGRES_DB=eatwell
      # - POSTGRES_USER=xxx
      # - POSTGRES_PASSWORD=...
  
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    restart: always
    tty: yes
    stdin_open: yes