# Generated by Django 3.2 on 2023-04-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='食谱名')),
                ('ingredient', models.CharField(max_length=200, verbose_name='食材')),
                ('step', models.TextField(max_length=1000, verbose_name='步骤')),
            ],
        ),
    ]
